import { Inter } from "next/font/google";
import localfont from "next/font/local";
import Header from "../../components/ui/Header";
import Footer from "../../components/ui/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const space = localfont({
	src: [
		{
			path: "../../public/fonts/SpaceGrotesk-VariableFont_wght.ttf",
		},
	],
	variable: "--font-space",
});

const saira = localfont({
	src: [
		{
			path: "../../public/fonts/SairaSemiCondensed-Regular.ttf",
		},
	],
	variable: "--font-saira",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={`${space.variable} ${saira.variable}`}>
			<body className={inter.className}>
				<main className="box-border px-[6rem] 2xl:px-[10rem]">
				<Header />
					{children}
				<Footer />
					</main>
			</body>
		</html>
	);
}
